x-baseService: &baseService
  restart: always
  healthcheck:
    interval: 1s
    timeout: 2s
    retries: 10

services:
  db:
    <<: *baseService
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}

  api:
    <<: *baseService
    build:
      context: ./
    environment:
      - SERVER_PORT=${SERVER_PORT}
    command: ["npm", "run", "test"]
    depends_on:
      db:
        condition: service_healthy
